name: Build and Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish to Docker Repository
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: phedri/sdtd-kafka
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
